# Generated by Django 5.2 on 2025-05-31 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drestapp', '0002_extractedevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('airline_name', models.CharField(max_length=50)),
                ('flight_date', models.DateField()),
                ('scheduled_departure_airport', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_departure_code', models.CharField(blank=True, max_length=10, null=True)),
                ('scheduled_departure_time', models.DateTimeField(blank=True, null=True)),
                ('gate_number_departure', models.CharField(blank=True, max_length=10, null=True)),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_arrival_airport', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_arrival_code', models.CharField(blank=True, max_length=10, null=True)),
                ('scheduled_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_gate', models.CharField(blank=True, max_length=10, null=True)),
                ('arrival_belt_number', models.CharField(blank=True, max_length=10, null=True)),
                ('baggage_checkin_starttime', models.TimeField(blank=True, null=True)),
                ('baggage_checkin_endtime', models.TimeField(blank=True, null=True)),
                ('boarding_pass_info', models.CharField(blank=True, max_length=100, null=True)),
                ('checkin_tag_number', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_boarding_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_boarding_time_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_boarding_time_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
