# Generated by Django 5.2 on 2025-06-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drestapp', '0003_flightrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightrecord',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.RemoveField(
            model_name='flightrecord',
            name='actual_boarding_time',
        ),
        migrations.RemoveField(
            model_name='flightrecord',
            name='baggage_checkin_endtime',
        ),
        migrations.RemoveField(
            model_name='flightrecord',
            name='baggage_checkin_starttime',
        ),
        migrations.RemoveField(
            model_name='flightrecord',
            name='boarding_pass_info',
        ),
        migrations.RemoveField(
            model_name='flightrecord',
            name='checkin_tag_number',
        ),
        migrations.RemoveField(
            model_name='flightrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flightrecord',
            name='scheduled_boarding_time_end',
        ),
        migrations.RemoveField(
            model_name='flightrecord',
            name='scheduled_boarding_time_start',
        ),
        migrations.AddField(
            model_name='flightrecord',
            name='status',
            field=models.CharField(default='Scheduled', max_length=20),
        ),
    ]
