# Generated by Django 5.2 on 2025-06-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drestapp', '0004_rename_updated_at_flightrecord_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightrecord',
            name='status',
        ),
        migrations.AlterField(
            model_name='flightrecord',
            name='flight_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
