# Generated by Django 5.2 on 2025-06-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drestapp', '0007_gmailmessage_airline_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailmessage',
            name='airline_name',
        ),
        migrations.RemoveField(
            model_name='gmailmessage',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='gmailmessage',
            name='flight_number',
        ),
    ]
