# Generated by Django 5.2 on 2025-06-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('subscription_info', models.JSONField()),
                ('p256dh', models.TextField(blank=True, null=True)),
                ('auth', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='flightstatusrecord',
            old_name='arrival_time',
            new_name='scheduled_arrival_time',
        ),
        migrations.RenameField(
            model_name='flightstatusrecord',
            old_name='departure_time',
            new_name='scheduled_departure_time',
        ),
        migrations.AddField(
            model_name='flightstatusrecord',
            name='actual_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightstatusrecord',
            name='actual_departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightstatusrecord',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
