# Generated by Django 5.2 on 2025-06-19 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_pushsubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapidAPISubscription',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_on', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapidapi_subscription', to='flights.flightstatusrecord')),
            ],
        ),
    ]
