# Generated by Django 5.2 on 2025-06-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_rapidapisubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightstatusrecord',
            old_name='actual_arrival_time',
            new_name='actual_arrival_time_local',
        ),
        migrations.RenameField(
            model_name='flightstatusrecord',
            old_name='actual_departure_time',
            new_name='actual_departure_time_local',
        ),
        migrations.RenameField(
            model_name='flightstatusrecord',
            old_name='scheduled_arrival_time',
            new_name='scheduled_arrival_time_local',
        ),
        migrations.RenameField(
            model_name='flightstatusrecord',
            old_name='scheduled_departure_time',
            new_name='scheduled_departure_time_local',
        ),
    ]
