# Generated by Django 5.2 on 2025-06-11 03:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightStatusRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_number', models.CharField(max_length=10)),
                ('airline_name', models.CharField(max_length=100)),
                ('departure_airport', models.CharField(max_length=100)),
                ('departure_iata', models.CharField(max_length=10)),
                ('departure_gate', models.CharField(blank=True, max_length=10, null=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_airport', models.CharField(max_length=100)),
                ('arrival_iata', models.CharField(max_length=10)),
                ('arrival_gate', models.CharField(blank=True, max_length=10, null=True)),
                ('arrival_baggage_belt', models.CharField(blank=True, max_length=10, null=True)),
                ('arrival_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
