# Generated by Django 5.2 on 2025-05-21 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('schedule', 'Schedule'), ('deadline', 'Deadline'), ('appointment', 'Appointment'), ('renewal', 'Renewal'), ('due', 'Due'), ('receipt', 'Receipt'), ('delivery', 'Delivery'), ('task', 'Task'), ('other', 'Other')], db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
