# Generated by Django 5.2 on 2025-04-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drestapp', '0003_customuser_expires_at_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='expires_at',
        ),
    ]
