# Generated by Django 5.2 on 2025-06-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drestapp', '0005_remove_flightrecord_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightrecord',
            old_name='flight_date',
            new_name='scheduled_date',
        ),
    ]
