# Generated by Django 5.2 on 2025-06-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drestapp', '0006_rename_flight_date_flightrecord_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailmessage',
            name='airline_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gmailmessage',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailmessage',
            name='flight_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
